# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/k3tzchen/nichts/discussions/categories/your-thoughts
    about: '"Report" anything off-topic in the discussions.'
